#define CHANNELS 4
#define BUTTONS_PER_CHANNEL 3
#define LED_PER_CHANNEL 1

#define GLOBAL_PULLUP true



#define MAX_INPUT_PINS  (CHANNELS*BUTTONS_PER_CHANNEL)
#define MAX_OUTPUT_PINS  (CHANNELS*LED_PER_CHANNEL)



